version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: runner
    environment:
      ENV: "local"
      WEB_PORT: ":8000"
      DB_CONNECTION: "${DB_CONNECTION}"
      GH_ORG_NAME: "hitachisolutionsamerica"
      GH_TOKEN: "${GH_TOKEN}"
      PROJECT_ID: "${PROJECT_ID}"
      DATA_PULL_JOB_CRON: "*/2 * * * *"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
  db:
    image: postgres:alpine3.20
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ghcharts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - backend
volumes:
  data:
networks:
  backend: